// Bundles src/parse-worker.js and the parsers it requires into one script and
// writes it to lib/worker-source.js as a string, so every build (JupyterLab,
// Notebook 6, Streamlit, the demo site) can start the worker from a Blob with
// no bundler-specific worker support. Run after tsc: node core/build-worker.js
const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, 'src');
const modules = {};
function add(name) {
  const file = name.endsWith('.js') ? name : name + '.js';
  if (file in modules) return;
  const code = fs.readFileSync(path.join(src, file), 'utf8');
  modules[file] = code;
  for (const m of code.matchAll(/require\(["']\.\/([\w-]+(?:\.js)?)["']\)/g)) add(m[1]);
}
add('parse-worker.js');

const body = Object.entries(modules)
  .map(([file, code]) => JSON.stringify(file) + ': function (module, exports, require) {\n' + code + '\n}')
  .join(',\n');
const bundle =
  '(function () {\nvar defs = {\n' + body + '\n};\nvar cache = {};\n' +
  'function req(name) { var f = /\\.js$/.test(name) ? name : name + ".js"; f = f.replace(/^\\.\\//, "");\n' +
  '  if (cache[f]) return cache[f].exports; var m = cache[f] = {exports: {}}; defs[f](m, m.exports, req); return m.exports; }\n' +
  'req("parse-worker.js");\n})();\n';
fs.mkdirSync(path.join(__dirname, 'lib'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'lib', 'worker-source.js'),
  '// Generated by core/build-worker.js; do not edit.\nmodule.exports = ' + JSON.stringify(bundle) + ';\n');
console.log('worker-source.js:', Object.keys(modules).join(', '), '(' + bundle.length + ' bytes)');
